theme: jekyll-theme-midnight
title: GraSP
description: 

grasp1title: I SÃ£o Paulo School on Gravitational Physics

github:
  is_project_page: false

collections:
  minicourses:
    output: true
    
defaults:
  - scope:
      path: "2024"
    values:
      layout: "grasp1"      
  - scope:
      path: ""
    values:
      layout: "default"
