theme: jekyll-theme-midnight
title: GraSP
description: Official website for the SÃ£o Paulo School on Gravitational Physics
plugins:
  - jekyll-seo-tag
email: graspschool@gmail.com

socials:
  - label: 'YouTube'
    src: https://www.youtube.com/channel/UCX13hxDoULJQisYEwBKpwfg
    sort: 'youtube'
    icon: 'fa-brands fa-youtube'
    show: true

github:
  is_project_page: false

collections:
  minicourses:
    output: true
  sections:
    output: true
    permalink: /:year/:name/
    
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: "2024"
    values:
      year: 2024
      show: true
  - scope:
      path: "2025"
      show: true
    values:
      year: 2025
