theme: jekyll-theme-midnight
title: GraSP
description: Official website for the SÃ£o Paulo School on Gravitational Physics
plugins:
  - jekyll-seo-tag
email: graspschool@gmail.com

socials:
  - label: 'YouTube'
    src: https://www.youtube.com/channel/UCX13hxDoULJQisYEwBKpwfg
    sort: 'youtube'
    icon: 'fa-brands fa-youtube'
    show: true

github:
  is_project_page: false

collections:
  minicourses:
    output: true
    
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      type: minicourses
    values:
      layout: "workshop"